### ISSUE TITLE
0.2.0 Roadmap

### ISSUE THREAD

**Issue by Selivanof** [Selivanof/Salonicraft#1]
This is a list of all the planned fixes/additions for version 0.2.0:

- [ ] Refactor all occurrences of "frapes" to "frappes"
- [ ] Customize the restoration and status effects for all the consumables introduced with this mod
- [ ] Reduce the cinnamon tree's spawn rate and add it to the flower forest biome
